"""Create initial AI Reception tables."""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.types import Uuid

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def uuid_type():
    return Uuid(as_uuid=True)


def upgrade() -> None:
    op.create_table("organizations", sa.Column("id", uuid_type(), primary_key=True), sa.Column("name", sa.String(200), nullable=False), sa.Column("slug", sa.String(100), nullable=False, unique=True), sa.Column("description", sa.Text()), sa.Column("phone", sa.String(50)), sa.Column("email", sa.String(320)), sa.Column("address", sa.String(500)), sa.Column("timezone", sa.String(64), nullable=False, server_default="UTC"), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_index("ix_organizations_slug", "organizations", ["slug"])
    op.create_table("departments", sa.Column("id", uuid_type(), primary_key=True), sa.Column("organization_id", uuid_type(), sa.ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False), sa.Column("name", sa.String(200), nullable=False), sa.Column("description", sa.Text()), sa.Column("contact", sa.String(200)), sa.Column("location", sa.String(300)), sa.Column("active", sa.Boolean(), nullable=False, server_default=sa.true()))
    op.create_index("ix_departments_organization_id", "departments", ["organization_id"])
    op.create_table("users", sa.Column("id", uuid_type(), primary_key=True), sa.Column("organization_id", uuid_type(), sa.ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False), sa.Column("name", sa.String(200), nullable=False), sa.Column("email", sa.String(320), nullable=False, unique=True), sa.Column("password_hash", sa.String(255), nullable=False), sa.Column("role", sa.String(30), nullable=False, server_default="reception"), sa.Column("department_id", uuid_type(), sa.ForeignKey("departments.id", ondelete="SET NULL")), sa.Column("active", sa.Boolean(), nullable=False, server_default=sa.true()), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_index("ix_users_organization_id", "users", ["organization_id"]); op.create_index("ix_users_email", "users", ["email"]); op.create_index("ix_users_role", "users", ["role"]); op.create_index("ix_users_department_id", "users", ["department_id"])
    op.create_table("visitors", sa.Column("id", uuid_type(), primary_key=True), sa.Column("organization_id", uuid_type(), sa.ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False), sa.Column("name", sa.String(200)), sa.Column("phone", sa.String(50)), sa.Column("email", sa.String(320)), sa.Column("preferred_language", sa.String(10), nullable=False, server_default="en"), sa.Column("first_seen", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("last_seen", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_index("ix_visitors_organization_id", "visitors", ["organization_id"])
    op.create_table("conversations", sa.Column("id", uuid_type(), primary_key=True), sa.Column("organization_id", uuid_type(), sa.ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False), sa.Column("visitor_id", uuid_type(), sa.ForeignKey("visitors.id", ondelete="CASCADE"), nullable=False), sa.Column("channel", sa.String(20), nullable=False, server_default="web"), sa.Column("status", sa.String(30), nullable=False, server_default="active"), sa.Column("started_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("ended_at", sa.DateTime(timezone=True)), sa.Column("assigned_department", uuid_type(), sa.ForeignKey("departments.id", ondelete="SET NULL")))
    op.create_index("ix_conversations_organization_id", "conversations", ["organization_id"]); op.create_index("ix_conversations_visitor_id", "conversations", ["visitor_id"]); op.create_index("ix_conversations_status", "conversations", ["status"]); op.create_index("ix_conversations_assigned_department", "conversations", ["assigned_department"])
    op.create_table("messages", sa.Column("id", uuid_type(), primary_key=True), sa.Column("conversation_id", uuid_type(), sa.ForeignKey("conversations.id", ondelete="CASCADE"), nullable=False), sa.Column("role", sa.String(20), nullable=False), sa.Column("content", sa.Text(), nullable=False), sa.Column("language", sa.String(10), nullable=False, server_default="en"), sa.Column("intent", sa.String(60)), sa.Column("confidence", sa.Float()), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_index("ix_messages_conversation_id", "messages", ["conversation_id"])
    op.create_table("appointments", sa.Column("id", uuid_type(), primary_key=True), sa.Column("organization_id", uuid_type(), sa.ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False), sa.Column("conversation_id", uuid_type(), sa.ForeignKey("conversations.id", ondelete="SET NULL")), sa.Column("visitor_id", uuid_type(), sa.ForeignKey("visitors.id", ondelete="CASCADE"), nullable=False), sa.Column("department_id", uuid_type(), sa.ForeignKey("departments.id", ondelete="RESTRICT"), nullable=False), sa.Column("requested_staff", sa.String(200)), sa.Column("appointment_date", sa.Date(), nullable=False), sa.Column("appointment_time", sa.Time(), nullable=False), sa.Column("purpose", sa.Text(), nullable=False), sa.Column("status", sa.String(20), nullable=False, server_default="pending"), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_index("ix_appointments_department_slot", "appointments", ["department_id", "appointment_date", "appointment_time"])
    op.create_table("tickets", sa.Column("id", uuid_type(), primary_key=True), sa.Column("organization_id", uuid_type(), sa.ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False), sa.Column("conversation_id", uuid_type(), sa.ForeignKey("conversations.id", ondelete="SET NULL")), sa.Column("visitor_id", uuid_type(), sa.ForeignKey("visitors.id", ondelete="CASCADE"), nullable=False), sa.Column("department_id", uuid_type(), sa.ForeignKey("departments.id", ondelete="RESTRICT"), nullable=False), sa.Column("category", sa.String(100)), sa.Column("title", sa.String(240), nullable=False), sa.Column("description", sa.Text(), nullable=False), sa.Column("priority", sa.String(20), nullable=False, server_default="medium"), sa.Column("status", sa.String(20), nullable=False, server_default="open"), sa.Column("assigned_user", uuid_type(), sa.ForeignKey("users.id", ondelete="SET NULL")), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("documents", sa.Column("id", uuid_type(), primary_key=True), sa.Column("organization_id", uuid_type(), sa.ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False), sa.Column("filename", sa.String(255), nullable=False), sa.Column("title", sa.String(255), nullable=False), sa.Column("file_type", sa.String(100), nullable=False), sa.Column("source", sa.String(500)), sa.Column("status", sa.String(30), nullable=False, server_default="pending"), sa.Column("uploaded_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("processed_at", sa.DateTime(timezone=True)))


def downgrade() -> None:
    for table in ("documents", "tickets", "appointments", "messages", "conversations", "visitors", "users", "departments", "organizations"):
        op.drop_table(table)
